### ISSUE TITLE
draft init should rewrite default packs

### ISSUE THREAD

**Issue by errordeveloper** [Azure/draft#105]
Last week I've tried `examples/node`, and got a weird NPM error... Today I've noticed that @kris-nova has fixed the issue with downgrade of Node base image, so I've ran `make bootstrap && make `, followed by `bin/draft init --upgrade`.
Next I've done `(cd examples/node && rm -rf Dockerfile draft.toml chart/ && draft create)`, but the `Dockerfile` didn't reflect the change I was expecting.
I've resolved the issue with `rm -rf ~/.draft && bin/draft init`, but I think the use experience can be improved, I'd expect `~/.draft/packs` to be overwritten on `draft init` (at least for the default packs).

**Comment by bacongobbler** [comment]
We have intentionally decided not to do this because

A) the developer may want to modify the default packs on their local machine
B) we want to work on a `draft pack` plugin that will better manage the install/upgrade/removal story of the default packs.

#2 should cover the problems you are facing.

**Comment by bacongobbler** [comment]
One other note: this should be bubbled up to the user in #6 to inform them of this intentional behaviour.
