### ISSUE TITLE
distro packages?

### ISSUE THREAD

**Issue by squillace** [Azure/draft#161]
From the original launch blog: https://azure.microsoft.com/en-us/blog/streamlining-kubernetes-development-with-draft/#comment-3338065825

**Comment by bacongobbler** [comment]
Docker images exist at [docker.io/microsoft/draft](https://hub.docker.com/r/microsoft/draft/) and the user can run `helm install chart/` from source code onto their cluster if they wish, but we are not recommending that due to the problems already being seen in #152.

**Comment by bacongobbler** [comment]
Not sure what the linux distro packages comment means, though. Like `apt-get install draft`?

**Comment by squillace** [comment]
1. that was the ask, I believe. Seems like a point in time thing -- stash it; maybe it happens, but in the future when we're ready.
2. I will argue for a metapackage, yes, but point in time thing. :-)

**Comment by squillace** [comment]
priorities in my mind (just a shot in dark)
1. brew recipe
2. apt-get/deb.
3. rpm
4. Windows builds get a chocolatey https://chocolatey.org/. 
5. dotnet "import"....

**Comment by bacongobbler** [comment]
ok, so to form this into a checklist of action items:

 - [x] hombrew (done; do `brew tap azure/draft` and `brew install azure/draft/draft`)
- [ ] apt-get/deb
- [ ] Chocolatey (tracked in #335)

rpm and dotnet won't make sense here since those are language package managers.

Also as a side note, I've been keeping the [GoFish](https://gofi.sh) package for Draft up to date with the latest release, which can install Draft on Windows/Mac/Linux with `gofish install draft`.
