### ISSUE TITLE
Iteration feature: draft recreate

### ISSUE THREAD

**Issue by squillace** [Azure/draft#214]
Use-case: I'm developing, and at some point while I iterate I decide I need another implementation here that will affect the original chart I made for the service. Now I need a `draft recreate [--retain-original-charts]` command to rebuild the chart/Dockerfile and so on, and potentially retain what you had before (although it was up to you to do the git work).

Discuss. :-)

**Comment by bacongobbler** [comment]
I'm not quite sure I follow. Can you explain what you mean by "I need another implementation that will affect the original chart"?

Are you looking for a rollback feature? If so `helm rollback` already does this so it sounds like a matter of documenting it.

**Comment by squillace** [comment]
then `draft take-backs` should call out to `helm rollback`.  :-P

Seriously, what if you want to modify some of the values in the values.yml file? Easiest example I can think of is to move the file into a different repo, changing the value of the source in chart.yml?

Basically, anything that, if `draft create` were called again, would change the chart/info. Or the Dockerfile, as well, necessitating a modification of one of the previously created files. We could force them to repoen the file and change it, of course, but that's kinda hostile for a tool where we enabled them to create them in the first place.

Am I way off? I can go create an example...

**Comment by bacongobbler** [comment]
> Basically, anything that, if draft create were called again, would change the chart/info. Or the Dockerfile, as well, necessitating a modification of one of the previously created files.

If you call `draft create` a second time on a repo, nothing will be modified because the project has already been bootstrapped. :)

```
><> draft create
--> chart directory already exists. Ready to sail!
```

> Seriously, what if you want to modify some of the values in the values.yml file? Easiest example I can think of is to move the file into a different repo, changing the value of the source in chart.yml?

If you want to modify the values provided in values.yaml, you modify them and call `draft up` again. `draft create` is just a command to bootstrap an application. After the application has been bootstrapped, the user calls `draft up`. Think of it as the equivalent of the following:

- `git init`
- `helm create`
- `rails new`
- `python manage.py startapp <appname>`

At this point, this is how the developer workflow looks like:

- user calls `draft create` on an app, then never calls it again
- user calls `draft up` to upload the app to kubernetes, bundling and deploying a Helm release
- user makes changes to source code, then calls `draft up` again to update the application

If you could create an example that perhaps clarified where you're coming from, I'd be happy to take a look! Perhaps we're just getting lost in translation.

**Comment by squillace** [comment]
Likely. I shall.

**Comment by bacongobbler** [comment]
ping, any update on this?

**Comment by squillace** [comment]
ping back: there will be this week. Wasn't while on vacation, no. :-)

**Comment by bacongobbler** [comment]
double ping

**Comment by squillace** [comment]
@bacongobbler, have thought about it and it was based on a misunderstanding of what's going on. Naturally. Close; I'll reopen an issue once I can write the user stories.
