### ISSUE TITLE
Helm chart cannot be linted

### ISSUE THREAD

**Issue by mstrzele** [Azure/draft#227]
`helm lint` doesn't allow to store Helm chart in `chart` directory. The name of the directory should be the same as the name of the chart.

```
$ helm lint chart
helm lint chart
==> Linting chart
[ERROR] Chart.yaml: directory name (chart) and chart name (draftd) must be the same
```

**Comment by bacongobbler** [comment]
This was actually an intentional design decision for the first part. We had originally assumed it was a [bug in Helm](https://github.com/kubernetes/helm/issues/1979) because `helm install ./chart/` works just fine, so it was assumed to be a bug.

There's a bit more of a discussion in https://github.com/Azure/draft/issues/219#issuecomment-313554646 on how we could fix this.
