### ISSUE TITLE
make randomly generated app names less random

### ISSUE THREAD

**Issue by michelleN** [Azure/draft#292]
Earlier in Draft history, there was discussion around using the directory name as the app name but there are some issues with that. After discussing with the team, it might be best to make the randomly generated app name be composed as follows `directoryName-random-thing` to give the user a little more context on what they're deploying using Draft. 

User experience: If you cloned a github repo called `twitter-clone` and ran a `$ draft create` inside of that directory, then the randomly generated app name might look like: `twitter-clone-angry-panda`.

**Comment by bacongobbler** [comment]
Just to add to this discussion, we've found from user feedback that the randomly generated names on `draft create` is confusing to the end user (why is my app name "sad-gorilla" instead of "my-app-name"?).

In most cases, the typical user workflow involves fetching down the application from a repository. For example, a python app that generates UUIDs would end up with the following directory structure after being fetched from github:

```
uuid-generator/
  app.py
  requirements.txt
  setup.py
  README.md
  app/
    __init__.py
  tests/
    __init__.py
    app_tests.py
```

The application name should be something relevant to the end-user. In 80% of cases, that would be the subdirectory name.

We propose that the default application name should be the subdirectory name (in this case, `uuid-generator`). However, if the user wants to generate a random name, then we could hide the existing functionality behind a feature flag like `draft create --gimme-a-name`, and if the user wants to give a different name, they can use `draft create --app my-app-name` as it works today.

Any other thoughts on this proposal, @michelleN?

**Comment by squillace** [comment]
why not prompt for a name on `draft create` with the default bracket being the dirname? As to the random name thing, just tack those on after whatever the name is. I think it is very low pri to help people understand the concept of _a guid_ here. :-) Plus, I won't let go of the `wonky-donkey` I got yesterday. I won't.

**Comment by bacongobbler** [comment]
Because it's one extra step in the user's workflow. The precedent is that every other dev tool centered around ease of deployment (Heroku, Zeit, dokku) all create an (auto-generated) application name for you with the option to explicitly create aliases or an alternative name through a command-line option. They're all designed around extreme ease of use, which is also what Draft is after. Having to prompt for information is "burdensome" and feels more clunky.

If we're positioning Draft as a tool for sysadmins to deploy applications, then more explicit control through prompts would make more sense.

**Comment by bacongobbler** [comment]
We now do this by default on `draft create` and the feedback from the community has been that this was a good move forward for Draft. Closing!
