### ISSUE TITLE
draft.yaml instead of draft.toml

### ISSUE THREAD

**Issue by nikolay** [Azure/draft#326]
The Kubernetes ecosystem is using YAML already. Why introduce yet another fancy configuration format? And what's wrong with JSON if you don't like YAML?

**Comment by bacongobbler** [comment]
We've learned a few things from using YAML in Helm. Here's a few war stories that justify why we are using TOML instead of other conventional markup languages commonly used in the Kubernetes community...

I can say from experience that debugging a YAML file written with improper or mixed indentation is the root of all evil, and has caused more developer frustrations than any other markup language. I can't count how many times I've seen Kubernetes users in Slack accidentally use tabs instead of spaces (and vice versa) and end up with obscure YAML parser errors. TOML does not care about indentation, which is a *really* welcome change for a simple markup language.

Secondly, the YAML spec is over 23,000 words. It's bloated, complex, and not at all "simple" or "obvious" to the user on its syntax. There are over [9 different ways to skin the proverbial cat](https://stackoverflow.com/a/21699210/2853424) in YAML, and because it is so complex most parsers will not support every feature. We (and users in general) only need 1 way to write a multi-line string. In TOML, it's just

```
message = """This is
a multi-line
string."""
```

Simple, right?

There is an excellent blog post by Martin Tournoij who explains the many intricacies and pitfalls of YAML, which I frequently point others to when asked this question: https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html

> And what's wrong with JSON if you don't like YAML?

I love JSON and it certainly has its place, but it is not a human-readable markup language by any stretch. You can't write comments in JSON. That's a non-starter for a file that's meant to be used by developers to express how their application is deployed to production. At the end of the day, we're writing a library for developers, not machines. For projects that stand up infrastructure like [acs-engine](https://github.com/Azure/acs-engine) or [kops](https://github.com/kubernetes/kops), JSON is an excellent fit.

However, don't take my word for gospel. I'm genuinely interested in hearing your opinion on why we should use YAML instead of TOML. Perhaps my (no-so-subtle) jaded opinion can be swayed. I do not want to turn this discussion into a flamewar of "vim vs emacs", but in my opinion, there are features (or lack thereof) in TOML that make it seem like a much more fitting choice than YAML.

**Comment by nikolay** [comment]
Don't get me wrong! I don't like either - including HCL! YAML is bloated, JSON is limited, TOML looks nice (except its, by my taste, ugly double square brackets), but lacks a decent toolchain. For example, JSON might be limited, but there are jq, JMESPath, Jsonnet, and others. Anyway, it's not about the format, we can argue forever which one is better, but about the number of configuration formats in a single project.

**Comment by bacongobbler** [comment]
Closing this as answered. If there's technical limitations with TOML we can revisit this discussion.
