### ISSUE TITLE
.7 RC: for ruby app, output steams logs so much you can't use the console

### ISSUE THREAD

**Issue by squillace** [Azure/draft#328]
On ubuntu 17.10/oh-my-zsh, for all the example apps the `draft connect` experience is great. But for the ruby app, the logs stream out onto the console in a way such that you can't use the console to grab the info you want. 

Might want to implement either the `--spew` true|false switch, or else understand why the ruby app streams 200 responses, but the others don't. Dunno. 

![image](https://user-images.githubusercontent.com/1422718/30410110-f4fd5a1e-98bd-11e7-83d9-4ec75c454f1e.png)

**Comment by bacongobbler** [comment]
This is also true for the python example, FWIW. Both apps have a liveness/readiness probe pointed at / and get probed every 10 seconds if I recall.

@michelleN perhaps we should revisit this design at some point? I could see this being an issue eventually where the user needs to keep scrolling up in order to find the listen address.

**Comment by michelleN** [comment]
Yeah, the immediate issue here is the liveness/readiness probes. Let's fix that problem using this issue to track it. I've added an issue to address your concern about getting url info in #338. I had thought about this but didn't want to address it in the MVP. It's a great thought though and I made a suggestion in that issue. Let me know what you think @bacongobbler
