### ISSUE TITLE
Option to specify a local port for "draft connect"

### ISSUE THREAD

**Issue by isutton** [Azure/draft#429]
Currently `draft connect` binds the remote port in a random local port.

In order to help developers, it would be helpful to specify a local port in `draft connect`. Some use case:

* Front-end developer running the server part of his application remotely and locally developing the front-end bits, probably with webpack development server acting as a reverse proxy to the local port bound to the remote development Pod.

**Comment by seanknox** [comment]
the helm kube client doesn't allow overriding the local port in a portforward tunnel, so the options for implementing are:

1. allow specifying local tunnel port in `k8s.io/helm/pkg/kube`
2. replace helm kube client with k8s.io/client-go (which allows specifying local port)

After talking with @michelleN we think the using client-go here makes sense in the short term. When `connect` moves into beta we can revisit this approach and see if that's still a good idea.

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/helm/pull/3213 fixes that upstream FYI. You might be able to take that work into consideration :)

**Comment by seanknox** [comment]
Oh awesome and timely!

**Comment by michelleN** [comment]
#521 adds a -c flag to specify which container to connect to. There was a question about what to do if there are multiple containers involved and I recommend we create tunnels to all containers by default. Does anyone have thoughts around that?

If we agree that we want to create tunnels to all containers by default then we'll want to take a step back and re-think this experience a bit. One option is to use the container port specified in the manifest as the port we'd want to connect to locally as well by default instead of choosing something random (so port 8080 on a container would map to 8080 on your machine only choosing something random is 8080 is unavailable on your machine). A way to override default behavior on the command line could be to add the `-p [port]:[port]` syntax like docker does in order to bind a desired port. We can also add a way to override default behavior using the `[port]:[port]` syntax in the draft.toml file (which just means adding more details to #472 )

This scenario only takes into account us connecting to one application pod at a time. This scenario gets much more hairy when we do `draft up` and `draft connect` in a different directory on a different service (or application) in which case we might either get more random port mappings or have to specify overrides. In my head, this an advanced use case and we'd have to determine first how users want to interact with their services. Would you do a `draft up` on many services but a `draft connect` on only one or are folks wanting the `draft up && draft connect` experience on multiple services at a time? If the latter, are folks okay with random port mappings in that scenario or configuring throught draft.toml and the command line?

**Comment by radu-matei** [comment]
Closed #521 in favour of #528, which:

- adds draft connect -c flag
- if a container is specified, start a tunnel to the container's first port and get logs from that container
- if no container is specified, start tunnels to the first port of all containers in pod and get logs from all containers

Regarding the local port - I see the upstream Helm PR is a bit stale - I can easily switch to the `client-go` implementation and add this - thoughts?

(Personal opinion - I wouldn't configure the port I want to bind to in `draft.toml`, but when when running the connect command).

**Comment by radu-matei** [comment]
Created a PR (#536) that adds the `-p` flag for `draft connect` - it switches out the Helm tunnel implementation for a custom one, which accepts a local port as argument when forwarding a remote port.

**Comment by bacongobbler** [comment]
closed via #575
