### ISSUE TITLE
Draft 0.8.0 for Windows

### ISSUE THREAD

**Issue by yaprigal** [Azure/draft#433]
Hi, 
Any plans to updated version of draft v.0.8.0 for Windows?

Thanks

**Comment by bacongobbler** [comment]
Hey there!

Due to some current issues with running Draft on Windows (see #406), we have dropped official Windows support in v0.8.0. We are still continuing to build and release Windows binaries, but given the current state of the project, we intend to target MacOS/Linux support out of the gate, with Windows support as an added bonus if anyone wants to tackle the problems associated with running Draft in that OS.

Canary builds for Windows can be found here: https://azuredraft.blob.core.windows.net/draft/draft-canary-windows-amd64.tar.gz

I'm going to close this and ask anyone to direct discussion towards #406. That way we can have one ticket to discuss the blockers for adding Windows support for Draft. Thanks! 😄

**Comment by mgolois** [comment]
any update on Draft for windows?

**Comment by bacongobbler** [comment]
you can follow #406 for status updates. :)
