### ISSUE TITLE
Homebrew distribution doesn't respect $DRAFT_HOME

### ISSUE THREAD

**Issue by iameli** [Azure/draft#449]
Is this expected behavior? I'm curious why it's a different binary at all.

```
> echo $DRAFT_HOME
/Users/elinostreams/.draft

# direct download

> curl -LO 'https://azuredraft.blob.core.windows.net/draft/draft-v0.9.0-darwin-amd64.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.6M  100 14.6M    0     0  1291k      0  0:00:11  0:00:11 --:--:-- 1172k
> tar xzf draft-v0.9.0-darwin-amd64.tar.gz
> darwin-amd64/draft version -c
Client: &version.Version{SemVer:"v0.9.0", GitCommit:"6a6b387d84cc7530b45bfff704bd1d71e36082ed", GitTreeState:"clean"}
> darwin-amd64/draft home
/Users/elinostreams/.draft

# homebrew

brew install draft
[snip]
==> Summary
🍺  /usr/local/Cellar/draft/0.9.0: 6 files, 61.0MB, built in 3 seconds

> draft version -c
Client: &version.Version{SemVer:"v0.9.0", GitCommit:"6a6b387d84cc7530b45bfff704bd1d71e36082ed", GitTreeState:"clean"}
> draft home
/usr/local/etc/draft
```

**Comment by bacongobbler** [comment]
This would be due to how [homebrew sets up the client](https://github.com/Azure/homebrew-draft/blob/0a8de4cbf5502fbd740023907ee8f8a95c6c489e/Formula/draft.rb#L13). In essence, homebrew writes a script called `draft` and puts it in your $PATH which hardcodes DRAFT_HOME to its local config directory. If you want direct access to the binary to change DRAFT_HOME, you'll want to look under `libexec` where homebrew is installed to get the right path to the binary, though this may go against homebrew's convention of writing configuration in $HOME.

```
><> DRAFT_HOME=/tmp /usr/local/Cellar/draft/0.8.0/bin/draft home
/usr/local/etc/draft
><> DRAFT_HOME=/tmp /usr/local/Cellar/draft/0.8.0/libexec/draft home
/tmp
```

In a sense, this is expected behaviour by design, yes. Draft is still respecting DRAFT_HOME; just not the one you set in the environment :)

**Comment by bacongobbler** [comment]
Just curious though; is there any particular reason why you'd prefer $DRAFT_HOME to use $HOME/.draft? Just trying to get a sense if there's a reason behind changing DRAFT_HOME from what homebrew expects and whether this is something we can/should accommodate or not.

**Comment by iameli** [comment]
The biggest reason is I needed Draft to work on two user accounts on my Mac and they were fighting for ownership on the default `$DRAFT_HOME` directory. Perhaps that should be filed as a different bug.
