### ISSUE TITLE
draft in homebrew fails to install

### ISSUE THREAD

**Issue by naveensrinivasan** [Azure/draft#519]
I am trying to install draft from homebrew and it is failing with this.

```
==> Tapping azure/draft
Cloning into '/usr/local/Homebrew/Library/Taps/azure/homebrew-draft'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/azure/homebrew-draft/Formula/draft-canary.rb
undefined method `strip' for nil:NilClass
Error: Cannot tap azure/draft: invalid syntax in tap!
```

**Comment by bacongobbler** [comment]
Hey! I think this may be due to connectivity issues to the internet. the draft-canary formula relies on [fetching the version](https://github.com/Azure/homebrew-draft/blob/4cc4f00f575e7c5c33fc6f3e1c68e72c00fc2c06/Formula/draft-canary.rb#L12-L14) from Azure Blob Storage.

Can you try again and see if it's a connection issue?

**Comment by naveensrinivasan** [comment]
@bacongobbler Great! Solved. Thanks
