### ISSUE TITLE
prompt for user input on `draft plugin remove`

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#553]
```
><> draft plugin install https://github.com/bacongobbler/draft-init-minikube
Installed plugin: init-minikube
><> draft plugin remove init-minikube
Removed plugin: init-minikube
```

Instead of making auto-accepting user input, we should probably prompt and gate it behind an `--auto-accept` or `-y` flag. That way it's one extra step from accidentally removing a plugin

**Comment by michelleN** [comment]
Is there a precedent for having this kind of gate? I only ask because I'm partial to have the user take the least amount of steps possible to achieve a goal. I can understand putting a gate on something that may be detrimental for a production set up (example: deleting a Helm release) but I don't think deleting a plugin is a big deal. What do you think?

**Comment by bacongobbler** [comment]
Makes sense. Since we're not actually removing resources from the cluster this is a good default. Closing!
