### ISSUE TITLE
Possibility to mount a folder so that maven builds are faster

### ISSUE THREAD

**Issue by eimarfandino** [Azure/draft#696]
It seems not possible to mount an external folder to speed up maven builds. Every time we run draft up it has to re-download all maven dependencies again making the build process slow.

**Comment by bacongobbler** [comment]
This is actually an intentional design when working with containers. Generally speaking, it's up to the application developer to figure out the best path forward for caching layers between two calls to `draft up`. This can be utilized through [the Docker layer cache](https://thenewstack.io/understanding-the-docker-cache-for-faster-builds/). So for example, if I have a python app that installs dependencies which are independent of my source code, it can be optimized with the following Dockerfile:

```
COPY requirements.txt /usr/src/app/
WORKDIR /usr/src/app
RUN pip install -r requirements.txt

COPY . /usr/src/app
```

This way, my dependencies are updated only when I modify requirements.txt or I supply the --no-cache flag to `docker build`. Does that make sense?

**Comment by bacongobbler** [comment]
Closing this as answered; please feel free to re-open with any thoughts/concerns! We love to hear feedback so this conversation is a good starter. :)
