### ISSUE TITLE
Relative Dockerfile path fails to build

### ISSUE THREAD

**Issue by EvanDarwin** [Azure/draft#720]
I'm currently unable to build a docker image if it's in a relative path on Windows... 😢 

```
PS > draft up
...
app-dev: Building Docker Image: FAIL ❌ (1.0000s)

PS > draft logs 01CCKHJMBRJZGQ7G7PAKJSBP0W
2018/05/03 10:42:43 error while building: Error response from daemon: Cannot locate specified Dockerfile: ./api/Dockerfile

PS > docker build ./api/
# works fine
Successfully built 8f8f4524e2f7

PS > draft version
&version.Version{SemVer:"v0.14.0", GitCommit:"e7a92f6b2f05a23f4cd9cc15fc24eb98d628e5d7", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
Good catch. I think @radu-matei found out about this too when he was testing out debugging Draft with the VSCode extension at KubeCon.

**Comment by radu-matei** [comment]
Yes, the issue is not only on Windows, and it is actually a known bug in the Docker code we're vendoring that given the relative paths of the Dockerfile and context, returns the absolute paths.

I'll have to investigate whether newer versions of the said package solve this issue and come back with some updates here.

(Also updated the title of the issue to reflect that it's not a Windows-only problem).
