### ISSUE TITLE
RFC: adding built-in docker registry , do not dependent thirdparty docker registry

### ISSUE THREAD

**Issue by netroby** [Azure/draft#82]
Is it possible to add a built-in docker registry inside kubernet cluster, no third party docker registry need. 

For enterprise usage, we often not allow to put our image outside or to the third party docker registry. 

So if we can set up a built-in docker registry inside our kubernete cluster , it will be very useful.

**Comment by bacongobbler** [comment]
It is not possible at this time. We attempted this and removed it in earlier versions for two reasons:

1) Unless the registry is backed by tls, it would require the docker daemons running on each node in kubernetes to allow insecure communication on the kubenet (not something we can do programmatically)
2) everyone has an opinion on how they want to deploy their registry to their cluster, whether it's HA, fault-tolerant, HIPAA compliance, tls, etc.

Because of those 2 points (mostly because of the first though), I initially wanted others to install a registry chart on their own and configure it manually.

That being said, if someone knows a way, I'd love a PR!

**Comment by Disturbing** [comment]
+1 on this. (first comment on the repro, new user, so THANKS for building this in advance)

But if a proposal and solid solution is presented here (unfortunately don't have one off the top of my head at this moment) getting draft to the state where you can easily do draft init, draft create, draft up on my already setup helm/k8s for both Minikube or normal cluster would be a solid achievement.

**Comment by bacongobbler** [comment]
Yeah @michelleN and I tossed around some ideas yesterday. We want to make the dev cluster experience (I.e. Minikube) a solid experience. The cloud providers have their own registries, but minikube right now is suffering a bit.
