### ISSUE TITLE
We should support dotnet build packs

### ISSUE THREAD

**Issue by seanknox** [Azure/draft#84]
A number of folks asked about this after the launch. No idea on the feasibility of this right now...

**Comment by bacongobbler** [comment]
If someone has a generic docker image to deploy any C# project as a docker image similar to python's onbuild image then I'm all for a PR.

**Comment by alexpilotti** [comment]
Hi @seanknox @bacongobbler, here's a PR adding .NET Core support #159

**Comment by noelbundick** [comment]
@alexpilotti - I was hacking around on this today as well - wanted to go ahead & commit my working in-progress in the event that there's anything useful you'd like to pull into your PR: https://github.com/noelbundick/draft/commit/a097712e1f72a118d077414f9044c97633e18fbb

My Dockerfile has a few bits to let you run 'draft up' from any folder (ie - the project doesn't have to be named WebApplication.dll). I think this is pretty nice given that Draft makes things easy by default

I encountered some problems with the livenessProbe - Kubernetes kept killing my pods until I added an initialDelaySeconds of 60 or so. I was also using the dotnet:latest image rather than aspnetcore-build, so that may explain the difference in startup time

**Comment by alexpilotti** [comment]
@noelbundick thanks for sharing your thoughts and code! I was also thinking about a clean way to avoid hardcoding the DLL name, it's definitely a requirement moving forward. I'll be happy to review and include your changes.
About the initialDelaySeconds, I'll do more tests as well and get back tomorrow with the results. 

As a side note, I'm testing this Starter Pack on top of #158, as I need to run draft on Windows.

**Comment by alexpilotti** [comment]
@noelbundick I did more tests and as result I increased the resources requests / limits memory to 256Mi and also set the livenessProbe to 60 initialDelaySeconds as you suggested.

**Comment by bacongobbler** [comment]
closing as #159 was merged.
